SYSTEM="icc normal"
#SYSTEM="icc fast"
#SYSTEM="gcc normal"
#SYSTEM="gcc fast"

ifeq ($(SYSTEM), "icc normal")
	CC=icc
	CFLAGS=-O0 -openmp -Wall -std=c99
endif

ifeq ($(SYSTEM), "icc fast")
	CC=icc
	CFLAGS=-fast -openmp -Wall -std=c99
endif

ifeq ($(SYSTEM), "gcc normal")
	CC=gcc
	CFLAGS=-O0 -fopenmp -Wall -std=c99
endif

ifeq ($(SYSTEM), "gcc fast")
	CC=gcc
	CFLAGS=-O3 -march=core2 -fomit-frame-pointer -static -fopenmp -Wall -std=c99
endif
